#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password:
  h2.console.enabled: true
  cache:
    cache-names: dish, restaurant
    caffeine:
      spec: maximumSize=500, expireAfterAccess=600s

  data.rest:
    basePath: /api
    defaultPageSize: 20
    returnBodyOnCreate: true

logging:
  level:
    root: WARN
    su.bzz.restaurantvoting: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true
